name: UUIDSwapper
api-version: '1.21.8'
main: me.itstautvydas.uuidswapper.loader.UUIDSwapperPaper
version: '${version}'
description: '${description}'
author: ItsTauTvyDas
folia-supported: true
website: ${website}