package me.itstautvydas.uuidswapper.enums;

public enum FallbackUsage {
    ON_CONNECTION_ERROR,
    ON_INVALID_UUID,
    ON_BAD_UUID_PATH,
    ON_UNKNOWN_ERROR,
    ON_BAD_STATUS,
    ON_BAD_PROPERTIES,
    ON_SERVICE_RATE_LIMITED,
    ON_SUB_SERVICE_RATE_LIMITED,
    ON_SUB_SERVICE_TIMEOUT,
    ON_SERVICE_TIMEOUT
}
